kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.fullname | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{ .Values.prometheusLabelKey }}: {{ .Values.fullname | quote }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      {{ .Values.prometheusLabelKey }}: {{ .Values.fullname | quote }}
  template:
    metadata:
      labels:
        {{ .Values.prometheusLabelKey }}: {{ .Values.fullname | quote }}
        name: {{ .Values.fullname | quote }}
    spec:
      serviceAccountName: {{ .Values.fullname | quote }}
      terminationGracePeriodSeconds: 60
      containers:
      - image: {{ .Values.deployment.image.repository | quote }}
        name: fakos
        imagePullPolicy: Always
        env:
          - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: {{ .Values.deployment.resources.requests.memory | quote }}
            cpu:  {{ .Values.deployment.resources.requests.cpu | quote }}
          limits:
            memory: {{ .Values.deployment.resources.limits.memory | quote }}
            cpu: {{ .Values.deployment.resources.limits.cpu | quote }}