fullname: fakos-metrics-exporter
namespace: kube-system
prometheusLabelKey: prometheus
deployment:
  image:
    repository: registry.gitlab.com/christiantragesser/fakos
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      memory: 64Mi
      cpu: 30m
    limits:
      memory: 128Mi
      cpu: 60m
service:
  name: metrics
  type: ClusterIP
  port: 8000
